language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g bower
  - bower install
script:
  - xvfb-run polymer test
before_deploy:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: lan-party-uma
    token: $FIREBASE_TOKEN
    on:
      branch: master