language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli firebase-tools
  - bower install
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: lan-party-uma
    token: $FIREBASE_TOKEN
    on:
      branch: master